version: '3'
services:
  makemkv:
    image: jlesage/makemkv:latest
    container_name: makemkv
    ports:
      - "5800:5800"
    volumes:
      - /home/jaimerios/Docker/makemkv/config:/config:rw
      - /home/jaimerios/Docker/makemkv/output:/output:rw
    devices:
      - /dev/sr0:/dev/sr0
      - /dev/sg6:/dev/sg6
    environment:
      - AUTO_DISC_RIPPER=0
      - MAKEMKV_KEY=M-utfFdge_NBD1PgOT9QgExLIXZI6oEQADg42aE109AoNh6NvPakgXq5mMDxGO9LKFH@
    restart: no
